version: '3.8'
services:
  eureka-server:
    image: dockerspringgcp-eurekaserver:0.0.1-SNAPSHOT
    build: eurekaserver/
    ports:
      - 8761:8761
  eureka-client:
    image: dockerspringgcp-eaurekaclient:0.0.1-SNAPSHOT
    build: eaurekaclient/
    depends_on:
      - eureka-server
      - journal-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
    ports:
      - 8081:8081
  journal-server:
    build: journal_server/
    image: dockerspringgcp-journal_server:0.0.1-SNAPSHOT
    depends_on:
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
    ports:
      - 8080:8080