version: '3'
services:
  eureka-server:
    image: dockerspringgcp-eurekaserver:0.0.1-SNAPSHOT
    build: eurekaserver/
    ports:
      - 8761:8761
  eureka-client:
    image: dockerspringgcp-eaurekaclient:0.0.1-SNAPSHOT
    build: eaurekaclient/
    volumes:
      - ./config-data:/var/config-data
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
        -Dspring.cloud.config.server.native.searchLocations=/var/config-data
    depends_on:
      - eureka-server
      - journal-server
    ports:
      - 8888:8888
  journal-server:
    build: journal_server/
    image: dockerspringgcp-journal_server:0.0.1-SNAPSHOT
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - 8080:8080
